### ISSUE TITLE
Date format example is ambiguous

### ISSUE THREAD

**Issue by jucie** [upcrob/fsq#1]
Home page states how to use _modified_:

_modified (format: '01/02/2006' or '01/02/2006 15:04:05')_

here the reader can't possibly know if the format is DD/MM/YYYY or MM/DD/YYYY.

(I would prefer YYYY/MM/DD, by the way. Then I would never have any doubt about the order.)

**Comment by upcrob** [comment]
The weirdness of this is derived from Go's reference time format: https://golang.org/pkg/time/

Still, you're right in that it makes sense to provide more clear documentation and error messages to reflect this.  I've made an update for this.
